#include<cstdio>
using namespace std;
int main()
{
    printf("input n\n");
    printf("input m\n");
    printf("a = 0\n");
    printf("b = 1\n");
    printf("s = 0\n");
    printf("d = s >= n\n");
    printf("e = s >= n\n");
    printf("z = d != e\n");
    printf("if z goto 6\n");
    printf("e = s >= n\n");
    printf("z = d != e\n");
    printf("if z goto 6\n");
    printf("e = s >= n\n");
    printf("z = d != e\n");
    printf("if z goto 6\n");
    printf("e = s >= n\n");
    printf("z = d != e\n");
    printf("if z goto 6\n");
    printf("e = s >= n\n");
    printf("z = d != e\n");
    printf("if z goto 6\n");
    printf("e = s >= n\n");
    printf("z = d != e\n");
    printf("if z goto 6\n");
    printf("e = s >= n\n");
    printf("z = d != e\n");
    printf("if z goto 6\n");
    printf("e = s >= n\n");
    printf("z = d != e\n");
    printf("if z goto 6\n");
    printf("if d goto 91\n");
    printf("o = a + b\n");
    printf("p = a + b\n");
    printf("z = o != p\n");
    printf("if z goto 32\n");
    printf("z = o != p\n");
    printf("if z goto 32\n");
    printf("z = o != p\n");
    printf("if z goto 32\n");
    printf("z = o != p\n");
    printf("if z goto 32\n");
    printf("z = o != p\n");
    printf("if z goto 32\n");
    printf("z = o != p\n");
    printf("if z goto 32\n");
    printf("z = o != p\n");
    printf("if z goto 32\n");
    printf("z = o != p\n");
    printf("if z goto 32\n");
    printf("a = b\n");
    printf("b = o\n");
    printf("o = b %% m\n");
    printf("p = b %% m\n");
    printf("z = o != p\n");
    printf("if z goto 52\n");
    printf("z = o != p\n");
    printf("if z goto 52\n");
    printf("z = o != p\n");
    printf("if z goto 52\n");
    printf("z = o != p\n");
    printf("if z goto 52\n");
    printf("z = o != p\n");
    printf("if z goto 52\n");
    printf("z = o != p\n");
    printf("if z goto 52\n");
    printf("z = o != p\n");
    printf("if z goto 52\n");
    printf("z = o != p\n");
    printf("if z goto 52\n");
    printf("b = o\n");
    printf("o = s + 1\n");
    printf("p = s + 1\n");
    printf("z = o != p\n");
    printf("if z goto 71\n");
    printf("z = o != p\n");
    printf("if z goto 71\n");
    printf("z = o != p\n");
    printf("if z goto 71\n");
    printf("z = o != p\n");
    printf("if z goto 71\n");
    printf("z = o != p\n");
    printf("if z goto 71\n");
    printf("z = o != p\n");
    printf("if z goto 71\n");
    printf("z = o != p\n");
    printf("if z goto 71\n");
    printf("z = o != p\n");
    printf("if z goto 71\n");
    printf("s = o\n");
    printf("if 1 goto 6\n");
    printf("output a\n");
    return 0;
}